# ===== CONFIGURAÇÕES DO BLOG =====
title: QAWSED                 # nome do blog (aparece no topo e na aba)
description: Escreva aqui uma frase sobre o blog.
lang: pt-BR
timezone: America/Sao_Paulo
baseurl: ""                   # deixe vazio se o repositório for usuario.github.io
permalink: /diario/:title/    # endereço dos posts
exclude: [README.md]
